language: ruby
rvm:
  - 1.9.3
notifications:
  email:
    recipients:
      - parkerwightman@gmail.com
      - landonwilkins@gmail.com
script: 
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

